### ISSUE TITLE
Consider exempting more default labels

### ISSUE THREAD

**Issue by patcon** [probot/stale#112]
While it's more clear that maybe `bug` and `question` should probably be marked as stale if left alone (because hey, the world moves on). But should something that someone took the time to tag as `enhancement` be marked stale? I would love to see the defaults be a bit more thoughtful about what the minimum a small project might want to turn on might be.

**Comment by hiimbex** [comment]
I think the defaults serve more as example than actual defaults for many people, since so many projects use different labels. 

I also think over time, for example, an `enhancement` could become outdated or out of scope, so it's worth having the bot at least comment as a reminder. But you could add that or any label to the list of `exemptLabels` to prevent that from happening.

**Comment by patcon** [comment]
Related: https://github.com/probot/stale/issues/111#issuecomment-381373820
