### ISSUE TITLE
[feature] lock stale issues

### ISSUE THREAD

**Issue by tjallingt** [probot/stale#122]
As discussed here: https://twitter.com/mjackson/status/990467330814558209
It might be interesting to automatically lock stale/old issues in order to limit the noise for collaborators.

The api call for this seems quite simple: https://developer.github.com/v3/issues/#lock-an-issue

Maybe it should be a `lockStale: true` option?

**Comment by tjallingt** [comment]
If it is decided that this is something you'd like to merge I would love to dive into the code to implement it 👍

**Comment by Timer** [comment]
This will probably be closed, see https://github.com/probot/stale/pull/75.

**Comment by hiimbex** [comment]
> it seems to me that it would be great to give maintainers an alternative to outright closing issues...

I'm a little confused by this, because you can still comment on closed issues, while I would consider locking issues more extreme, as it prevents outside collaborators from commenting. 

You can also install lock and stale apps to work together in a way, in that they both check for activity the same way. Therefore I think the maintainers of stale would prefer to keep this unnecessary functionality out of stale itself, considering stale is already pretty complex.

I'm open to further discussion, if there's any reason that stale and lock can't work easily together, but closing until such evidence is provided (if it exists).

**Comment by ssbarnea** [comment]
To be honest, the lack of locking as a second stage after closing makes me wonder if I would not better use another app instead of stalebot, at least to keep the list of tools we need to configure and tune from time to time lower. Both of them work on the same type of data. Any suggestions for something that can do both, closing and later locking?
