### ISSUE TITLE
Does not unmark when activity on PR when using keywords pulls: and issues:

### ISSUE THREAD

**Issue by johlju** [probot/stale#134]
In this PR https://github.com/PowerShell/xSmbShare/pull/20#issuecomment-398221767 it did not remove the stale label 'abandoned' when there was activity on the PR (see [style.yml](https://github.com/PowerShell/xSmbShare/blob/dev/.github/stale.yml)). Looking at the code it seems is not using the `this.getConfigValue(type, 'staleLabel')' or similar to get the correct value.  

https://github.com/probot/stale/blob/628cbc9368f295b026da2e91d646ae1ed27cb136/index.js#L36-L37

@bkeepers Can I get your input on this one? Could this be the problem?

**Comment by hiimbex** [comment]
The line you linked to is checking to make sure the event wasn't stale bot adding a label that would otherwise count as activity. So in your case this `context.payload.action === 'labeled'` would be false since the actions would have been `issue_comment.created`.

The code that actually does the unmarking is [here](https://github.com/probot/stale/blob/master/lib/stale.js#L147), but after looking through this for a bit, I don't immediately see the issue. Let me know if you can reproduce this anywhere.

**Comment by johlju** [comment]
@hiimbex Thanks for looking at this - example of it not being removed can be seen here https://github.com/johlju/DebugApps/pull/16. Just commented on the PR but the label is not getting removed. Feel free to test/debug anyway you want in this repo, it is just a "lab" for testing/verifying Apps.

**Comment by hiimbex** [comment]
Hmmm just guessing, but looking at your stale.yml I see https://github.com/PowerShell/xSmbShare/blob/dev/.github/stale.yml#L7 in which you never plan to close the PR, so maybe that's causing this unmark run never to happen?

I'll try to look into this more shortly.

**Comment by johlju** [comment]
It could be, because it unmarks for issues, which is configured to be closed.

**Comment by johlju** [comment]
@hiimbex It looks like it actually works for pushed, but not other activity? 🤔 

I saw these below, where Stale actually correctly removed the abandoned label (both when user pushed).
https://github.com/PowerShell/xFailOverCluster/pull/177#event-1728461137
https://github.com/PowerShell/SqlServerDsc/pull/1052#event-1721261265

So isn't seeing the correct (all) events for example when commenting? 🤔

**Comment by johlju** [comment]
@hiimbex After seeing this issue a few times more, it seems is removed the "stale" label ('abanonded' in my case) when there is a push to a PR, but **it seems it does not remove the "stale" label when there is a "pull request comment" event**.

A comment was made here, but Stale did not remove the label.
https://github.com/PowerShell/CertificateDsc/pull/134#issuecomment-409640245

**Comment by johlju** [comment]
This is still an issue since the abandoned label is not removed when commenting on a pull request (as per my previous comment). 

*Updating so this issue is active.*

**Comment by hiimbex** [comment]
Sorry I haven't had time to look into this further. If you'd like to investigate and open a PR, I'd be happy to review it, otherwise I don't think it's likely this will be prioritized in the near future.

**Comment by infotexture** [comment]
@hiimbex [wrote](https://github.com/probot/stale/issues/134#issuecomment-402009020):

> Let me know if you can reproduce this anywhere.

I've seen similar behavior on issues in the _DITA Open Toolkit_ repository where the Stale bot is enabled, but does not reliably remove labels on activity, so the problem is apparently not limited to PRs.

In https://github.com/dita-ot/dita-ot/issues/2286#issuecomment-446669099, the Stale bot added a comment and label to an old issue as expected, but failed to remove the `stale` label a few days later when the original poster added a comment https://github.com/dita-ot/dita-ot/issues/2286#issuecomment-449577039, which should have removed the label according to the [Probot description](https://probot.github.io/apps/stale/):

> If the Issue or Pull Request is updated, or anyone comments, then the stale label is removed and nothing further is done until it becomes stale again.

Since the label was not removed, the issue was later closed although it shouldn't have been.

One of the project maintainers subsequently re-opened the issue, which the Stale bot noticed and removed the `stale` label. 

I double-checked the [configuration](https://github.com/dita-ot/dita-ot/blob/develop/.github/stale.yml#L24), but don't see anything that would seem to prevent Probot from removing the the `stale` label when comments are posted.

_— Any ideas?_

**Comment by max-sixty** [comment]
We're seeing the same bug here: https://github.com/pydata/xarray/issues/2797. It's happened on multiple issues.

I'm looking at the configurations between xarray and @infotexture to see if there's some similarity. We both use the `stale` label, which is not default. Could that be a cause?

Thanks for the awesome tool

**Comment by johlju** [comment]
Still relevant. Someone in the community just need to help resolve this. 😊

**Comment by max-sixty** [comment]
We haven't seen this again FWIW
