### ISSUE TITLE
Disable until due date

### ISSUE THREAD

**Issue by jhnns** [probot/stale#142]
Hi Probot maintainers 👋, nice work! 👍

I have a feature request 😁: It would be nice if I could disable the stale check by specifying a due date (maybe by using a command?). We have a lot of issues with different lifetimes in the same repo. The default setting of 90 days works pretty well for most of them, but there are also issues where we know that we won't work on it during the next 90 days. It would be nice to get rid of the staleness messages then until a certain date. 

What do you think?

**Comment by hiimbex** [comment]
Hi @jhnns!

Right now there's exempt labels, milestones, and projects that won't ever be marked as stale; you can also act differently on issues vs PRs. See more in the yml file: https://github.com/probot/stale#usage. I feel like adding a label like `long-term` to issues might work for your usecase?

Beyond these existing settings, we unfortunately do not have the bandwidth to work on something like this. I do encourage you to implement the feature yourself if you're truly interested, and if we can see it working/there's enough interest, we'd consider merging it in here.

Gonna close this out since there's no action to be taken on our end
