### ISSUE TITLE
Probot not closing issues

### ISSUE THREAD

**Issue by johnnyreilly** [probot/stale#184]
Heya!

First of all, thanks for probot - it's amazing!

I've had it installed and running on ts-loader for a couple of weeks now. It started out all guns blazing, marking things as wontfix and then closing them a week later. However it appears to have stopped closing older issues. I wonder if you might have any idea why? This is my `stale.yml`

https://github.com/TypeStrong/ts-loader/blob/master/.github/stale.yml

And here's my issues: https://github.com/TypeStrong/ts-loader/issues

As you can see lots of older issues are being left as is...

For example this one: https://github.com/TypeStrong/ts-loader/issues/54

Is marked as stale but hasn't been closed. I can't work out why...

**Comment by tcbyrd** [comment]
@johnnyreilly Is this working now? We were having some OOM issues on Stale so it would fail to work, but it should be resolved now.

**Comment by Aqours** [comment]
@tcbyrd I have the same problem. `markComment` and `closeIssue` don't work.
See 
https://github.com/Semibold/Weibo-Picture-Store/blob/master/.github/stale.yml
https://github.com/Semibold/Weibo-Picture-Store/issues/87

**Comment by tcbyrd** [comment]
@Aqours Your example is exactly why I want to make some updates to Stale. I tested your `stale.yml` and noticed the following errors, but there's currently nothing that reports this to you:

```
Error: ValidationError: child "closeComment" fails because ["closeComment" must be a string or false]
```

Since you have `true`, that's getting interpreted as a boolean, when what it wants is a string (a comment to use when it closes the issue). If you update that and/or just remove the `closeComment` field, it should start working.

**Comment by Aqours** [comment]
@tcbyrd Thanks. It works after setting closeComment to false

**Comment by tcbyrd** [comment]
Awesome! I'm going to close this since I _think_ we've resolved all the OOM issues that were causing it to crash. Anyone else please feel free to re-open this is you're still having problems.

**Comment by johnnyreilly** [comment]
Sorry for the delay in responding - I'm not sure the issue is resolved since I still have examples of stale but not closed issues: https://github.com/TypeStrong/ts-loader/issues/54

**Comment by tcbyrd** [comment]
@johnnyreilly That issue isn't labeled `wontfix`. The call to add the label probably failed while we were dealing with OOM issues, and since the bot's comment was added < 60 days ago it hasn't come up in the search for stale issues. Tomorrow is 60 days since Jan 19th, so it should get labeled again on tomorrow's sweep, or you can mark it `wontfix` manually today to see if it gets auto-closed on the next sweep. Providing a report of what Stale is doing on your repo is something I'm hoping to add as well. Right now if anything goes wrong it just fails silently with no way to re-try.
