### ISSUE TITLE
stale.yml doesn't take effect in apache/apisix

### ISSUE THREAD

**Issue by spacewander** [probot/stale#348]
Yesterday, I tried to enable the stale bot in Apache APISIX: https://github.com/apache/apisix/commit/fbb80fe8da33e75d57899474a3d1432a088a0690.

The commit is pushed 24 hours ago.

However, none of the issues become stale. Issues that are expected to be stale can be found there: 'https://github.com/apache/apisix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+updated%3A%3C2020-09-04:'

The [stale app configuration](https://github.com/marketplace/stale) is enabled by Apache Software Foundation's staff.

Could you help me to investigate this issue? Thanks!

**Comment by spacewander** [comment]
Ping @gr2m @JamesMGreene 
Would you please help me to investigate this issue?

The Apache Software Foundation's staff replied that Stale APP is already enabled on apache/apisix.

**Comment by gr2m** [comment]
I can't help with the stale app, sorry. We usually recommend folks to use the official stale action instead:
https://github.com/actions/stale

Will that work for you?

**Comment by spacewander** [comment]
Sorry, I am confused. It seems the README (https://github.com/probot/stale#usage) doesn't mention the stale action. What is the relation between the stale app and the action?

**Comment by gr2m** [comment]
The app was created before we had GitHub Actions. Due to its nature of needing a way to run tasks on a schedule to check for the stale issues, it's a perfect fit for GitHub Actions.

We discussed to deprecate the stale app in the past but I think we didn't because it's still used so widely. 

That's all I know sorry, I'm working on Probot core, I cannot help much with Stale

**Comment by spacewander** [comment]
It works! Thanks @gr2m
