### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by hiimbex** [probot/stale#57]
https://sentry.io/probot/stale/issues/325727830/

```
{"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3"}
```

Happen quite a bit in the past several hours, I looked into the recent audit code and didn't immediately see anything that would've caused this.

cc/ @bkeepers

**Comment by bkeepers** [comment]
It definitely started after I deployed #56, and the error is happening when trying to read `.github/config.yml`. I'm wondering if it's always been happening, but the try/catch that used to be wrapped around fetching the config was hiding it? I'm also noticing a lot of the errors are coming from the same account, which makes me think that it's someone that installed the integration pretty early on, and permissions have changed since then (If I remember right, the path of the config file changed pretty early on).

**Comment by bkeepers** [comment]
@HardieBoeve  :wave: could you do me a favor? Could you try uninstalling/reinstalling http://github.com/apps/stale on your account? Your account is the one I mentioned ☝️.

**Comment by HardieBoeve** [comment]
@bkeepers I just have uninstalled/reinstalled probot/stale on my account.

**Comment by bkeepers** [comment]
Thanks @HardieBoeve, that fixed it. I'm guessing you installed it back when the permissions were different.

**Comment by bkeepers** [comment]
@andris9 :wave: could you do me a favor? Could you try uninstalling/reinstalling http://github.com/apps/stale on @nodemailer? It is the other account that is hitting this error, and I suspect it's because the permissions changed after you originally installed it.

Thanks!

**Comment by andris9** [comment]
@bkeepers uninstaller/reinstalled. I hope it helps.

**Comment by bkeepers** [comment]
Thanks @andris9

**Comment by bkeepers** [comment]
@ukstudio :wave: could you do me a favor? Could you try uninstalling/reinstalling http://github.com/apps/stale on @spice-life? It is hitting this error, and I suspect it's because the permissions changed after you originally installed it.

**Comment by bkeepers** [comment]
There's not much else I can do about this right now, so closing. I've muted the error in sentry so it won't show up again unless this error happens >100 times within a week.
