### ISSUE TITLE
how to add stale for organizations?

### ISSUE THREAD

**Issue by fmv1992** [probot/stale#77]
Hello,

1. I have added probot to my account as indicated having:

    ~~~~~~
    [ok tick] Read access to metadata and single file
    [ok tick] Read and write access to issues and pull requests
    ~~~~~~

    And I'm an admin in an organization.

1. I have added the file `.github/stale.yml` to the organization I'm part of:

    https://github.com/python-mode/python-mode/tree/develop/.github

1. I have also waited for more than one hour for the bot to wake.

Still I have no results. Can you help me?

:)

**Comment by bkeepers** [comment]
Hey @fmv1992, it looks like you have the app installed on [fmv1992/python-mode](https://github.com/fmv1992/python-mode) and not [python-mode/python-mode](https://github.com/python-mode/python-mode). When you visit https://github.com/apps/stale/installations/new and pick the @python-mode org instead of your personal account.

Let me know if that doesn't fix it for you and I'll do a little more digging.

**Comment by fmv1992** [comment]
I believe that more than being an admin I have to be the owner of the organization in order for that option to be available.

I'll contact him and post here if my endeavour was successful.

Best,

**Comment by felker** [comment]
Is it necessary to be the owner of an Organization repository to enable it? Other GitHub Apps such as Codecov have worked with just admin access for me.
