### ISSUE TITLE
Validation Failed: The year 1918 is outside the accepted range

### ISSUE THREAD

**Issue by bkeepers** [probot/stale#81]
From https://sentry.io/probot/stale/issues/427330638/

```json
{
  "message": "Validation Failed",
  "errors": [{
    "message":"The year 1918 in \"1918-01-27T22:55:01\" is outside the accepted range 1970 to 2970.",
    "resource":"Search",
    "field":"q",
    "code":"invalid"
  }],
  "documentation_url":"https://developer.github.com/v3/search/"
}```

**Comment by tcbyrd** [comment]
I looked through several of these and they're all related to the the `PointCloudLibrary/pcl` repository. Looks like they changed the days to [100 years,](https://github.com/PointCloudLibrary/pcl/pull/2166) which is still outside of the Unix timestamp range.

@bkeepers I can take a crack at a PR for https://github.com/probot/stale/issues/79, but will also tell them to update their range to no earlier than 1970. This also relates back to https://github.com/probot/friction/issues/1. This setting is having the desired outcome, but only because the method raises an error which they don't see.

**Comment by bkeepers** [comment]
@tcbyrd the other thing we need to do is add guards for the config (#62). For this issue specifically, check that the date is within an acceptable range.

For now, I think stale should just refuse to run if it encounters an invalid config.

**Comment by tcbyrd** [comment]
Agreed. I was thinking this was the next step, especially given some of the other errors I've seen in sentry revolve around incorrect configs.
